name: update-documentation-site

on: [push]

jobs:
  update-documentation-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update documentation site version
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git clone https://github.com/userdashboard/userdashboard.github.io documentation
        cd documentation
        npm version patch
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        external_repository: "userdashboard/userdashboard.github.io"
        personal_token: ${{ secrets.DOCUMENTATION_PAT }}
        publish_dir: documentation
        publish_branch: master
        keep_files: true
